### ISSUE TITLE
01001000 01100001 01101100 01101100 01101111 00100000 01001101 01100001 01111000

### ISSUE THREAD

**Issue by EinWortspiel** [sintonis/greeter#1]
01001001 01100011 01101000 00100000 01101000 01100001 01100010 01100101 00100000 01100100 01100101 01101001 01101110 00100000 01001000 01000100 01001101 01001001 00100000 01001011 01100001 01100010 01100101 01101100 00100000 01100001 01110101 01110011 00100000 01100100 01100101 01101101 00100000 01010010 01100001 01110101 01101101 00100000 00110010 00110000 00110100 00100000 01100111 01100101 01101011 01101100 01100001 01110101 01110100 00001010 01010111 01100101 01101110 01101110 00100000 01100100 01110101 00100000 01100101 01110011 00100000 01110111 01101001 01100101 01100100 01100101 01110010 00100000 01110111 01101001 01101100 01101100 01110011 01110100 00101100 00100000 01100110 01101001 01101110 01100100 01100101 00100000 01101101 01101001 01100011 01101000

**Comment by MaxAtslega** [comment]
Okay... Das ist nicht gut... Wo finde ich dich?
